name: Node.js Package (NPM)
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@pickupmusic'
      - run: npm ci
      - run: git switch -c master
      - run: git config --global user.email "fabiosdcouto@gmail.com"
      - run: git config --global user.name "GitHub CI"
      - run: npm version patch -m "[RELEASE] v%s"
      - run: git push https://${{secrets.GH_TOKEN}}@github.com/Pickup-Music/metronome
      - run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}